# Generated by Django 3.0.5 on 2020-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200415_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=300)),
                ('description', models.TextField(default='')),
                ('place', models.TextField(default='')),
                ('photo', models.CharField(blank=True, default='', max_length=500)),
                ('category_id', models.IntegerField(default=1)),
                ('subcategory_id', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
