# Generated by Django 3.0.5 on 2020-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=100)),
                ('telegram_username', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
