# Generated by Django 3.0.5 on 2020-04-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('telegram_chat_id', models.CharField(max_length=100)),
                ('telegram_username', models.CharField(max_length=100)),
                ('profile_photo', models.CharField(default='https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png', max_length=200)),
                ('faculty', models.CharField(default='None', max_length=50)),
                ('gender', models.CharField(default='3', max_length=50)),
                ('year_of_study', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
